### ISSUE TITLE
Store limits on Device

### ISSUE THREAD

**Issue by FL33TW00D** [huggingface/ratchet#185]
We need to store a subset of `wgpu::Limits` on the Device, so that our kernels don't exceed dispatch limits.

**Comment by officialcjunior** [comment]
That makes sense: use the device-specific limits so that we don't hardcode numbers and exceed them while requesting for the adapter.

Now, I was trying to understand what needs to be changed from a code perspective. Here, from what I understand, we're already using the default device-specific limits for all except for these three parameters?

https://github.com/huggingface/ratchet/blob/2a626e6e88986a4596464e7737e954249646cdb1/crates/ratchet-core/src/gpu/device.rs#L65-L74

**Comment by FL33TW00D** [comment]
resolved in #202
